# Minimal royd image profile.
# The exact family-specific removal policy is generated by install-royd.sh from
# repository-owned package manifests and inherited here before filtering.
$(call inherit-product, vendor/royd/profile_policy.mk)

PRODUCT_PACKAGES := $(filter-out $(ROYD_MINIMAL_PACKAGES),$(PRODUCT_PACKAGES))
PRODUCT_PACKAGES_DEBUG := $(filter-out $(ROYD_MINIMAL_PACKAGES),$(PRODUCT_PACKAGES_DEBUG))
PRODUCT_VENDOR_PROPERTIES += ro.vendor.royd.image_profile=minimal
